icub-tech-iit/ergocub-software

.github/workflows/generate_models.yml
README.md
urdf/simmechanics/CMakeLists.txt
urdf/simmechanics/scripts/convertSTL.rb

This has to be ported to icub-models-generator too
For doing the conversion I used a (modified) version of https://github.com/cmpolis/convertSTL starting from [this commit](https://github.com/cmpolis/convertSTL/commit/b353f144bd14f77f1a0f3177dcc2969a0ffcf388)

Add stl convertion from ascii to binary

---

.github/workflows/generate_models.yml
CMakeLists.txt
tests/CMakeLists.txt
tests/ergocub-model-test.cpp
urdf/CMakeLists.txt
urdf/simmechanics/data/ergocub/ERGOCUB_all_options.yaml
urdf/simmechanics/data/ergocub/ERGOCUB_all_options_gazebo.yaml.in

This PR imports the consistency tests for the model generation.
I imported the tests by copying-pasting the [tests for icub3](https://github.com/robotology/icub-models-generator/blob/master/tests/icub-model-test.cpp)
Running the tests I corrected some axis orientations(#7) but some failures in the joint orientation cannot be fixed by simply inverting the axes.
Moreover, we have also discrepancies in the ft sensors orientation and `r/l_sole` alignment, for now I disabled the failing tests in order to not making fail the CI, but I think they have to be addressed in separate issues
It fixes #6

Enable test for model generation

---

urdf/simmechanics/data/ergocub/ERGOCUB_all_options.yaml

For now, we remove  the hip ft sensors from the model of `ergoCubSN000` since on the real robot the ones mounted are dummy
see https://github.com/icub-tech-iit/ergocub-software/issues/43#issuecomment-1422312202

ergoCubSN000: remove ft sensors in the legs

---

tests/ergocub-model-test.cpp
urdf/simmechanics/data/ergocub/ERGOCUB_all_options.yaml
urdf/simmechanics/data/ergocub/ERGOCUB_all_options_gazebo.yaml.in

In accordance to the real ergoCub, this PR reverses `camera_tilt` and `l_shoulder_yaw`, so that:
- Positive tilt points upwards
- Positive yaw rotates along an axis oriented towards the hand
Addresses: https://github.com/icub-tech-iit/ergocub-software/issues/47
cc @lrapetti

Reverse rotation of camera tilt and left shoulder yaw in URDF

---

urdf/simmechanics/data/ergocub/ERGOCUB_all_options.yaml
urdf/simmechanics/data/ergocub/ERGOCUB_all_options_gazebo.yaml.in

After some tests on gazebo in order to test whether the `waist_imu` was correctly put inside the urdf model, I found out an error in the rpy angles. This PR aims to fix this error. 
Now, by reading the accelerometer through `yarp read ... /ergocubSim/waist/inertials/measurements:o`, I'm able to read the gravity acceleration in the opposite direction of the y axis, in accordance to the cad.

Fix rpy angles of waist_imu

---

urdf/simmechanics/data/ergocub/conf/wrappers/motorControl/all-mc_remapper.xml
urdf/simmechanics/data/ergocub/conf/wrappers/motorControl/all-mc_remapper_ros2.xml

I added the `all-mc_remapper.xml` and `all-mc_remapper_ros2.xml` under `../urdf/simmechanics` since they existed only under `../urdf/ergoCub` and I updated the number of torso_joints from 3 to 2 after removing torso_pitch from conf files.

Update torso_joints number in all-mc_remapper.xml after removing torso_pitch

---

urdf/simmechanics/data/ergocub/ERGOCUB_all_options.yaml
urdf/simmechanics/data/ergocub/ERGOCUB_all_options_gazebo.yaml.in

This PR aims to fix the xsens reference frame mounted on the ergocub waist inside the urdf. 
I read the values streamed by the xsens both real and simulated (on gazebo) and the accelerometer values are coherent. To be sure, the new rf should be plotted in order to see whether it matches with the one on the robot.

Fix waist_imu_0 reference frame

---

urdf/simmechanics/data/ergocub/ERGOCUB_all_options.yaml
urdf/simmechanics/data/ergocub/ERGOCUB_all_options_gazebo.yaml.in

It fixes #131 
We fixed the frame of the lidar now the X point ahead as the other frames in the robot
We applied the patch on generation side and we didn't fixed the CAD for the issue of creo 9
cc @SimoneMic @pattacini

Fix lidar reference frame

---

urdf/simmechanics/data/ergocub/conf/estimators/wbd_ecub_sim.xml

This PR should fix wbd with ergoCubGazeboV1 since it didn't start (see https://github.com/icub-tech-iit/ergocub-software/issues/149).
With these changes, instead:

ergoCubGazeboV1: fix wholebodydynamics

---

tests/ergocub-model-test.cpp
urdf/simmechanics/data/ergocub/ERGOCUB_all_options.yaml
urdf/simmechanics/data/ergocub/ERGOCUB_all_options_gazebo.yaml.in
urdf/simmechanics/data/ergocub/SIM_ERGOCUB_1-0.xml

It fixes #146
This is the twin pr of  https://github.com/robotology/icub-models-generator/pull/243
- It adds the check that this alignment is maintained when the urdf is generated
- Export the frames for the ft sensors

ergoCubGazeboV1: make ft frame centered on z w/ the link frame

---

tests/ergocub-model-test.cpp

https://github.com/icub-tech-iit/ergocub-software/pull/158 silently changed the name of the FT sensors, i.e.:
* ergocub-software <= 0.3.3 names : l_arm_ft_sensor, r_arm_ft_sensor, l_leg_ft_sensor, l_foot_front_ft_sensor, l_foot_rear_ft_sensor, r_leg_ft_sensor, r_foot_front_ft_sensor, r_foot_rear_ft_sensor 
* ergocub-software >= 0.3.4 names : l_arm_ft, r_arm_ft, l_leg_ft, l_foot_front_ft, l_foot_rear_ft, r_leg_ft, r_foot_front_ft, r_foot_rear_ft
However, the names used in the ergocub-model-test.cpp were not updated. However, the tests were silently skipped due to the following logic, that skipped a test if a sensor was not present:
~~~cxx
// Depending on the ergocub model, the sensor could be absent
if (!comp.model().isFrameNameUsed(sensorName))
{
return true;
}
~~~

Fix name of FT sensors in FT sensor orientation test in  ergocub-model-test.cpp

---

urdf/creo2urdf/data/ergocub1_0/ERGOCUB_all_options.yaml
urdf/creo2urdf/data/ergocub1_0/ERGOCUB_all_options_gazebo.yaml
urdf/creo2urdf/data/ergocub1_0/ERGOCUB_all_options_minContacts.yaml
urdf/creo2urdf/data/ergocub1_1/ERGOCUB_all_options.yaml
urdf/creo2urdf/data/ergocub1_1/ERGOCUB_all_options_gazebo.yaml
urdf/creo2urdf/data/ergocub1_1/ERGOCUB_all_options_minContacts.yaml

While parsing the SDF generated out of the URDF files of ergoCub in Gazebo via sdformat, a warning is printed:
~~~
Warning [parser.cc:833] XML Attribute[name] in element[ray] not defined in SDF, ignoring.
~~~
See https://github.com/ami-iit/rod/issues/26 .
It turns out that we are adding a `name`  attribute to the `ray` element of the sdf, but this attribute is not supported, nor parsed (see http://sdformat.org/spec?ver=1.10&elem=sensor#sensor_ray). The `sensor` element (parent of `ray`) has already a `name` attribute, and that can be used to identify the sensor. I guess this happened as a copy&paste error due to thefact the camera element instead supports an optional name element (see http://sdformat.org/spec?ver=1.10&elem=sensor#sensor_camera), even if to be honest I find it a bit …

Fix ray-related warning printed by sdformat while parsing

---

urdf/creo2urdf/data/ergocub1_0/ERGOCUB_all_options.yaml
urdf/creo2urdf/data/ergocub1_0/ERGOCUB_all_options_gazebo.yaml
urdf/creo2urdf/data/ergocub1_0/ERGOCUB_all_options_minContacts.yaml
urdf/creo2urdf/data/ergocub1_1/ERGOCUB_all_options.yaml
urdf/ergoCub/robots/ergoCubSN001/model.urdf

It fixes #179 
Moreover, it removes all the `default` sensors from the ergoCubSN000 yaml, since that clause is not supported by `creo2urdf`

ergoCubSN001: simplify collision shape of feet

---

CHANGELOG.md
urdf/creo2urdf/data/ergocub1_0/ERGOCUB_all_options.yaml
urdf/creo2urdf/data/ergocub1_0/ERGOCUB_all_options_gazebo.yaml
urdf/creo2urdf/data/ergocub1_0/ERGOCUB_all_options_minContacts.yaml
urdf/creo2urdf/data/ergocub1_1/ERGOCUB_all_options.yaml
urdf/creo2urdf/data/ergocub1_1/ERGOCUB_all_options_gazebo.yaml
urdf/creo2urdf/data/ergocub1_1/ERGOCUB_all_options_minContacts.yaml
urdf/ergoCub/robots/ergoCubGazeboV1/model.urdf
urdf/ergoCub/robots/ergoCubGazeboV1_minContacts/model.urdf
urdf/ergoCub/robots/ergoCubSN000/model.urdf

It fixes #197
The strange thing it was that also in the V1.1 yaml there were `r/l_upperarm`

ergoCubV1*: correct names l/r_upperarm w/ r/l_upper_arm

---

tests/ergocub-model-test.cpp
urdf/creo2urdf/data/ergocub1_1/ERGOCUB_all_options.yaml
urdf/creo2urdf/data/ergocub1_1/ERGOCUB_all_options_gazebo.yaml
urdf/creo2urdf/data/ergocub1_1/ERGOCUB_all_options_minContacts.yaml
urdf/ergoCub/conf/ergocub.xml
urdf/ergoCub/robots/ergoCubGazeboV1_1/model.urdf
urdf/ergoCub/robots/ergoCubGazeboV1_1_minContacts/model.urdf
urdf/ergoCub/robots/ergoCubSN001/model.urdf

It fixes #200
As side effect this PR removes also the nws for ergocub 1.0, the optimal solution would be to have two different xml files (e.g. `ergocub1_0.xml`. `ergocub1_1.xml`.
But since this a temporary workaround that will be hopefully soon reverted we could avoid to add yet another xml file to be maintained.
What do you think about @traversaro @GiulioRomualdi @pattacini ?

ergoCubV1_1: remove ft sensors of the arms

---

tests/ergocub-model-test.cpp
urdf/creo2urdf/data/ergocub1_1/ERGOCUB_all_options.yaml
urdf/creo2urdf/data/ergocub1_1/ERGOCUB_all_options_gazebo.yaml
urdf/creo2urdf/data/ergocub1_1/ERGOCUB_all_options_minContacts.yaml
urdf/ergoCub/conf/ergocub.xml
urdf/ergoCub/robots/ergoCubGazeboV1_1/model.urdf
urdf/ergoCub/robots/ergoCubGazeboV1_1_minContacts/model.urdf
urdf/ergoCub/robots/ergoCubSN001/model.urdf

This reverts commit 6be5893296bdf465323ab3ca698745d7b74dc3a3.
cc @GiulioRomualdi

Revert "ergoCubV1_1: remove ft sensors of the arms"

---

app/ergoCubEmotions/CMakeLists.txt

@S-Dafarra pointed out that `ergoCubEmotions` configuration files were not installed in the same directory after https://github.com/icub-tech-iit/ergocub-software/pull/196. This fixes the error and makes the expressions run properly (tested locally on ergoCub) 
cc @GiulioRomualdi

Fix ergoCubEmotions installation dir

---

.github/workflows/gh-pages.yml

As per title, the gh-pages push will be done only once merged

Avoid pushing gh-pages when creating a PR

---

app/ergoCubEmotions/conf/config.ini
src/modules/ergoCubEmotions/ergoCubEmotions.cpp
src/modules/ergoCubEmotions/ergoCubEmotions.h

This should fix https://github.com/icub-tech-iit/ergocub-software/issues/213. I tried to launch the module after these changes on my laptop and the cpu consumption significantly decreased. 
To be tested on `ergocub-head`.

ergoCubEmotions: avoid reading videos at each update of the module

---

urdf/creo2urdf/data/ergocub1_0/ERGOCUB_all_options.yaml
urdf/creo2urdf/data/ergocub1_0/ERGOCUB_all_options_gazebo.yaml
urdf/creo2urdf/data/ergocub1_0/ERGOCUB_all_options_minContacts.yaml
urdf/creo2urdf/data/ergocub1_1/ERGOCUB_all_options.yaml
urdf/creo2urdf/data/ergocub1_1/ERGOCUB_all_options_gazebo.yaml
urdf/creo2urdf/data/ergocub1_1/ERGOCUB_all_options_minContacts.yaml
urdf/ergoCub/conf/ergocub.xml
urdf/ergoCub/conf/gazebo_ergocub_l_foot_front_ft_sensor_inertial.ini
urdf/ergoCub/conf/gazebo_ergocub_l_foot_rear_ft_sensor_inertial.ini
urdf/ergoCub/conf/gazebo_ergocub_r_foot_front_ft_sensor_inertial.ini
urdf/ergoCub/conf/gazebo_ergocub_r_foot_rear_ft_sensor_inertial.ini
urdf/ergoCub/conf/wrappers/inertials/left_foot-IMU_remapper.xml
urdf/ergoCub/conf/wrappers/inertials/left_foot-IMU_wrapper.xml
urdf/ergoCub/conf/wrappers/inertials/right_foot-IMU_remapper.xml
urdf/ergoCub/conf/wrappers/inertials/right_foot-IMU_wrapper.xml
urdf/ergoCub/robots/ergoCubGazeboV1/model.urdf
urdf/ergoCub/robots/ergoCubGazeboV1_1/model.urdf
urdf/ergoCub/robots/ergoCubGazeboV1_1_minContacts/model.urdf
urdf/ergoCub/robots/ergoCubGazeboV1_minContacts/model.urdf
urdf/ergoCub/robots/ergoCubSN000/model.urdf
urdf/ergoCub/robots/ergoCubSN001/model.urdf

Hi @Nicogene! I added the feet IMU on the urdf model. Unfortunately, I don't have creo on my PC so I cannot test the modification.

[ergoCubGazeboV1_*] Add feet IMU in the urdf model generation

---

urdf/creo2urdf/data/ergocub1_1/ERGOCUB_all_options.yaml
urdf/creo2urdf/data/ergocub1_1/ERGOCUB_all_options_gazebo.yaml
urdf/creo2urdf/data/ergocub1_1/ERGOCUB_all_options_minContacts.yaml
urdf/ergoCub/robots/ergoCubGazeboV1_1/model.urdf
urdf/ergoCub/robots/ergoCubGazeboV1_1_minContacts/model.urdf
urdf/ergoCub/robots/ergoCubSN001/model.urdf

They have been added by @GiulioRomualdi in;
- #217 
Using `xmlBlob` due to a bug in creo2urdf that has been fixed:
- https://github.com/icub-tech-iit/creo2urdf/pull/79 
- https://github.com/icub-tech-iit/creo2urdf/issues/77
Moreover seems that the ones adde in #217 were wrong:
- https://github.com/icub-tech-iit/creo2urdf/issues/77#issuecomment-1949929873

ergoCubSN001/GazeboV1_1*: add ft imu via `sensor`

---

README.md
urdf/creo2urdf/data/ergocub1_0/README.md
urdf/creo2urdf/data/ergocub1_1/README.md

I also refer to https://github.com/icub-tech-iit/cad-libraries/wiki/Prepare-PTC-Creo-Mechanism-for-URDF that now is a bit outdated (see https://github.com/icub-tech-iit/cad-libraries/issues/174), but eventually will be fixed.
cc @xela-95

Update documentation on the URDF generation from Creo CAD assemblies

---

urdf/creo2urdf/data/ergocub1_0/ERGOCUB_all_options.yaml
urdf/creo2urdf/data/ergocub1_0/ERGOCUB_all_options_gazebo.yaml
urdf/creo2urdf/data/ergocub1_0/ERGOCUB_all_options_minContacts.yaml
urdf/creo2urdf/data/ergocub1_1/ERGOCUB_all_options.yaml
urdf/creo2urdf/data/ergocub1_1/ERGOCUB_all_options_gazebo.yaml
urdf/creo2urdf/data/ergocub1_1/ERGOCUB_all_options_minContacts.yaml
urdf/ergoCub/conf/gazebo_ergocub_l_arm_ft_sensor_inertial.ini
urdf/ergoCub/conf/gazebo_ergocub_l_leg_ft_sensor_inertial.ini
urdf/ergoCub/conf/gazebo_ergocub_r_arm_ft_sensor_inertial.ini
urdf/ergoCub/conf/gazebo_ergocub_r_leg_ft_sensor_inertial.ini
urdf/ergoCub/conf/wrappers/inertials/alljoints-inertials_remapper.xml
urdf/ergoCub/conf/wrappers/inertials/alljoints-inertials_wrapper.xml
urdf/ergoCub/robots/ergoCubGazeboV1/model.urdf
urdf/ergoCub/robots/ergoCubGazeboV1_1/model.urdf
urdf/ergoCub/robots/ergoCubGazeboV1_1_minContacts/model.urdf
urdf/ergoCub/robots/ergoCubGazeboV1_minContacts/model.urdf
urdf/ergoCub/robots/ergoCubSN000/model.urdf
urdf/ergoCub/robots/ergoCubSN001/model.urdf

This is the twin of https://github.com/robotology/icub-models-generator/pull/264. In this PR were added:
- the .ini files for the inertials for the IMU sensors mounted on the FT of the arms and the legs. The ones of the feet were already added in:
-  https://github.com/icub-tech-iit/ergocub-software/pull/217
-  https://github.com/icub-tech-iit/ergocub-software/pull/222)
- the `alljoints-inertials_wrapper.xml` and `alljoints-inertials_remapper.xml` to wrap up the inertials measurements (I didn't added them to the xml used by the yarprobotinterface by default);
- for  ergoCub1.0 models (i.e. ergoCubGazeboV1, ergoCubGazeboV1_minContacts, ergoCubSN000): the `arms and legs IMU` as `XMLBlobs` in the .yaml and manually added to the urdf;
-  ergoCub1.1 models (i.e. ergoCubGazeboV1_1, …

[ergoCubSN00*/ergoCubGazeboV1*] Add alljoints-inertials to be aligned with real ergoCub

---

urdf/creo2urdf/data/ergocub1_0/base_1_0.yaml
urdf/creo2urdf/data/ergocub1_1/base_1_1.yaml
urdf/ergoCub/conf/gazebo_ergocub_l_arm_ft_sensor_inertial.ini
urdf/ergoCub/conf/gazebo_ergocub_l_leg_ft_sensor_inertial.ini
urdf/ergoCub/conf/gazebo_ergocub_r_arm_ft_sensor_inertial.ini
urdf/ergoCub/conf/gazebo_ergocub_r_leg_ft_sensor_inertial.ini

Fixing regression of https://github.com/icub-tech-iit/ergocub-software/pull/232 concerning the use of ergocub UDRF files on `gz-sim` through `gz-sim-yarp-plugins`.
Related issue https://github.com/robotology/gz-sim-yarp-plugins/issues/173
Related PR: https://github.com/icub-tech-iit/ergocub-software/pull/251
CC @traversaro

Fix alljoints inertials to work also on `gz-sim`

---

urdf/ergoCub/conf/gazebo_ergocub_l_arm_ft_sensor_inertial.ini
urdf/ergoCub/conf/gazebo_ergocub_l_leg_ft_sensor_inertial.ini
urdf/ergoCub/conf/gazebo_ergocub_r_arm_ft_sensor_inertial.ini
urdf/ergoCub/conf/gazebo_ergocub_r_leg_ft_sensor_inertial.ini

By checking if the modifications introduced by https://github.com/icub-tech-iit/ergocub-software/pull/253 were also working on the modern Gazebo, I found a mistake I made in https://github.com/icub-tech-iit/ergocub-software/pull/250.

Fix IMU parent link names for `gz-sim-yarp-plugins`

---

urdf/creo2urdf/data/ergocub1_0/base_1_0.yaml
urdf/creo2urdf/data/ergocub1_1/base_1_1.yaml
urdf/ergoCub/robots/ergoCubGazeboV1/model.urdf
urdf/ergoCub/robots/ergoCubGazeboV1_1/model.urdf
urdf/ergoCub/robots/ergoCubGazeboV1_1_minContacts/model.urdf
urdf/ergoCub/robots/ergoCubGazeboV1_2/model.urdf
urdf/ergoCub/robots/ergoCubGazeboV1_2_minContacts/model.urdf
urdf/ergoCub/robots/ergoCubGazeboV1_minContacts/model.urdf
urdf/ergoCub/robots/ergoCubSN000/model.urdf
urdf/ergoCub/robots/ergoCubSN001/model.urdf
urdf/ergoCub/robots/ergoCubSN002/model.urdf

Fix the position of the imu in the waist

---

CMakeLists.txt
tests/CMakeLists.txt
urdf/CMakeLists.txt

This PR adds support for configuring the `ergocub-software/urdf` folder as a standalone project with no dependency, useful if one wants just to install the ergocub models without requiring OpenCV and YARP. Furthermore, it also adds the `COMPILE_ergoCubModels` option, to compile `ergocub-software` without the models.
This options are meant for advanced users, so I think it is ok not to document then, advanced users interested in them can just read about them in the `CMakeLists.txt.

Support for configure and installing URDF models of ergocub without any dependencies

---

.gitignore
app/ergoCubEmotions/conf/config.ini
src/modules/ergoCubEmotions/ergoCubEmotions.cpp
src/modules/ergoCubEmotions/ergoCubEmotions.h
src/modules/ergoCubEmotions/idl.thrift

With this PR it is possible to draw simple elements in the expressions. 
At the moment I only added circles and "stadiums". It is possible to toggle the visibility and change the color from RPC
This is the result
https://github.com/user-attachments/assets/b231aab7-2323-4a0d-bd92-fe1aaa08efb2

Added possibility to draw basic circles and "stadiums" in the expressions

---

app/ergoCubEmotions/conf/config.ini
src/modules/ergoCubEmotions/ergoCubEmotions.cpp
src/modules/ergoCubEmotions/ergoCubEmotions.h

Before the actual video was shown only once, but the correct emotion was displayed because it was the last frame of the corresponding transition.
Also, I exploited maps instead of vectors to look for the available transitions.

Looping and preload of all media

---

src/modules/couplingXCubHandMk5/CMakeLists.txt

YARP 3.12 will be released with a change for which the device param parser generators generated by YARP 3.11 (and that are committed in this repo) do not work with YARP 3.12, see also https://github.com/robotology/yarp/pull/3225 . A simple trick to easily support both YARP 3.11 and 3.12 (to simplify migrations) is to change the default value of `ALLOW_DEVICE_PARAM_PARSER_GENERATION` (the CMake option that enables the generation of the device param parsers) to `ON` if YARP 3.12 is used. 
In this way, 3.11 users will continue to be able to use the committed version of the files, while YARP 3.12 users will still be able to compile, with the downside that they will have non-committed files that should pay attention not to commit. A possible alternative solution is to generate the device param …

Change default value of ALLOW_DEVICE_PARAM_PARSER_GENERATION based on YARP version to support both YARP 3.11 and 3.12
