urdf/simmechanics/data/ergocub/ERGOCUB_all_options.yaml, urdf/simmechanics/data/ergocub/ERGOCUB_all_options_gazebo.yaml.in
This PR exports the csys of the fingertips.
It fixes #9 
cc @xEnVrE @pattacini @Lawproto
=> Export SCSYS left and right hand

CHANGELOG.md, tests/ergocub-model-test.cpp, urdf/simmechanics/data/ergocub/conf/gazebo_ergocub_left_hand.ini, urdf/simmechanics/data/ergocub/conf/gazebo_ergocub_right_hand.ini
See https://github.com/robotology/robots-configuration/pull/436
It fixes #42
=> urdf: change the names of the joints of the hands in order to be compliant with the real robot

urdf/ergoCub/conf/estimators/wbd_ecub_sim.xml, urdf/ergoCub/conf/launch_wholebodydynamics_ecub.xml
=> add config files to launch wholebodydynamics externally

CHANGELOG.md, urdf/simmechanics/CMakeLists.txt, urdf/simmechanics/data/ergocub/ERGOCUB_all_options.yaml, urdf/simmechanics/data/ergocub/ERGOCUB_all_options_gazebo.yaml.in
This issue was due to a leftover of old link name of the forearm
It fixes #60
=> urdf: fix small inertia issues on left arm

urdf/simmechanics/data/ergocub/conf/gazebo_ergocub_torso.ini
=> urdf: fix torso joints order

README.md
cc @mebbaid @traversaro @Nicogene
=> Add instructions to run whole-body-dynamics in the readme

CHANGELOG.md, urdf/simmechanics/data/ergocub/ERGOCUB_all_options.yaml, urdf/simmechanics/data/ergocub/ERGOCUB_all_options_gazebo.yaml.in
=> urdf: fixed taxels exportations for pinkies

CHANGELOG.md, tests/ergocub-model-test.cpp, urdf/simmechanics/CMakeLists.txt, urdf/simmechanics/data/ergocub/ERGOCUB_all_options_gazebo.yaml.in, urdf/simmechanics/data/ergocub/conf/gazebo_ergocub_torso.ini, urdf/simmechanics/data/ergocub/conf/wrappers/motorControl/torso-mc_remapper.xml
Here is the resulting model
cc @GiulioRomualdi @lrapetti
=> Fix torso_pitch to 10 deg

urdf/ergoCub/conf/estimators/wbd_ecub_sim.xml
For consistency with https://github.com/icub-tech-iit/ergocub-software/pull/103 .
Fix https://github.com/icub-tech-iit/ergocub-software/issues/111 .
=> Remove torso_pitch from wholebodydynamics configuration files

.github/workflows/gh-pages.yml
The goal is to have a network like this:
Instead of the current state which is:
=> Better handling gh-pages branch

src/modules/ergoCubEmotions/ergoCubEmotions.cpp, src/modules/ergoCubEmotions/ergoCubEmotions.h
Fixes #138 
Still need to be tested on the robot.
=> Added mutex in the rpc call setEmotion.

tests/ergocub-model-test.cpp, urdf/simmechanics/CMakeLists.txt, urdf/simmechanics/data/ergocub/conf/estimators/wbd_ecub_sim.xml, urdf/simmechanics/data/ergocub/conf/gazebo_ergocub_torso.ini, urdf/simmechanics/data/ergocub/conf/wrappers/motorControl/all-mc_remapper.xml, urdf/simmechanics/data/ergocub/conf/wrappers/motorControl/torso-mc_remapper.xml
=> ergoCubGazeboV1: reenable torso_pitch

urdf/ergoCub/robots/ergoCubGazeboV1_1/model.urdf, urdf/ergoCub/robots/ergoCubGazeboV1_1_minContacts/model.urdf, urdf/ergoCub/robots/ergoCubSN001/model.urdf
As per title
It fixes #170 
cc @GiulioRomualdi @traversaro
=> ergoCubV1_1: fix identation

tests/ergocub-model-test.cpp, urdf/creo2urdf/data/ergocub1_1/ERGOCUB_all_options.yaml, urdf/creo2urdf/data/ergocub1_1/ERGOCUB_all_options_gazebo.yaml, urdf/creo2urdf/data/ergocub1_1/ERGOCUB_all_options_minContacts.yaml, urdf/ergoCub/robots/ergoCubGazeboV1_1/model.urdf, urdf/ergoCub/robots/ergoCubGazeboV1_1_minContacts/model.urdf, urdf/ergoCub/robots/ergoCubSN001/model.urdf
=> ergoCubV1_1: correct index_add joint

urdf/ergoCub/conf/gazebo_ergocub_depth_camera.ini, urdf/ergoCub/conf/sensors/gazebo_ergocub_rgbd_camera.ini
@xEnVrE made me notice that in #188 I modified an ini that is not used.
In this PR I modified the correct one and deleted the one that is unused
=> ergoCubV1*: fix configuration file of depth sensor

README.md
@akhilsathuluri did not know a conda binary package was available, it is probably useful to document it.
=> Document installation using conda binary packages

urdf/ergoCub/conf/estimators/wbd_ecub_sim.xml
As per the title, this PR enables the streaming of the arms wrenches 
cc @Nicogene @traversaro
=> [ergoCubGazeboV1X] Allow WBD publishing left and right arms external wrenches

doc/mkdocs/docs/CHANGELOG.md, mkdocs.yml
This PR adds the CHANGELOG tab in the website
=> Add CHANGELOG to the website

urdf/ergoCub/conf/wrappers/FT/left_foot-FT_remapper.xml, urdf/ergoCub/conf/wrappers/FT/left_leg-FT_remapper.xml, urdf/ergoCub/conf/wrappers/FT/right_foot-FT_remapper.xml, urdf/ergoCub/conf/wrappers/FT/right_leg-FT_remapper.xml
=> Add temperature sensors in FT leg remappers of ergoCub

urdf/creo2urdf/data/ergocub1_0/ERGOCUB_all_options.yaml, urdf/creo2urdf/data/ergocub1_1/ERGOCUB_all_options.yaml, urdf/creo2urdf/data/ergocub1_1/ERGOCUB_all_options_gazebo.yaml, urdf/creo2urdf/data/ergocub1_1/ERGOCUB_all_options_minContacts.yaml
This fixes https://github.com/icub-tech-iit/ergocub-software/issues/218
=> [ergoCubGazeboV1_*] Fix right_arm controlboard names

urdf/ergoCub/conf/ergocub_coupling_ros2.xml, urdf/ergoCub/conf/wrappers/motorControl/all-mc_remapper-coupling.xml, urdf/ergoCub/conf/wrappers/motorControl/all-mc_remapper_ros2-coupling.xml, urdf/ergoCub/conf/wrappers/motorControl/left_arm-mc_remapper-coupling.xml, urdf/ergoCub/conf/wrappers/motorControl/left_hand-coupling_handler.xml, urdf/ergoCub/conf/wrappers/motorControl/left_hand-mc_wrapper.xml, urdf/ergoCub/conf/wrappers/motorControl/right_arm-mc_remapper-coupling.xml, urdf/ergoCub/conf/wrappers/motorControl/right_hand-coupling_handler.xml
See:
- #178
- https://github.com/robotology/yarp/pull/3026
- https://github.com/robotology/yarp/pull/3085
=> Add configuration files for using the sw layer that handles the coupling

urdf/ergoCub/conf/ergocub.xml, urdf/ergoCub/conf/ergocub_coupling_ros2.xml, urdf/ergoCub/conf/ergocub_gz_sim.xml, urdf/ergoCub/conf/ergocub_ros2.xml
As per title, this is the twin of https://github.com/robotology/robots-configuration/pull/640
=> [ergoCubSN00*/ergoCubGazeboV1*] Include alljoints-inertials_wrapper/remapper in YRI xml files

urdf/ergoCub/conf/estimators/wbd_ecub_sim.xml
This behavior mimics what is done in ergoCubSN00*
=> Avoid to use joint acceleration in ergoCubSim

src/modules/ergoCubEmotions/ergoCubEmotions.cpp
It fixes #262
I didn't have the chance to test it since the robot is quite busy nowadays, but it should be safe to merge it
cc @S-Dafarra
=> ergoCubEmotions: handle portprefix parameter

urdf/ergoCub/robots/ergoCubGazeboV1/model.urdf, urdf/ergoCub/robots/ergoCubGazeboV1_minContacts/model.urdf, urdf/ergoCub/robots/ergoCubSN000/model.urdf
=> ergoCubV1: fix limits

urdf/creo2urdf/data/ergocub1_3/ERGOCUB_all_options.yaml, urdf/creo2urdf/data/ergocub1_3/base_1_3.yaml, urdf/ergoCub/robots/ergoCubGazeboV1_3/model.urdf, urdf/ergoCub/robots/ergoCubGazeboV1_3_minContacts/model.urdf
=> Update the YAML files in order to add the neck mk3 to gazeboV1_3 urdf

urdf/creo2urdf/data/common/minContacts_addon.yaml, urdf/ergoCub/robots/ergoCubGazeboV1_1_minContacts/model.urdf, urdf/ergoCub/robots/ergoCubGazeboV1_3_minContacts/model.urdf
=> Change minContacts addon in order to use empty instead of a box of 0 dimension
